server:
  port: 9001
  
spring:
  application:
    name: shop-consumer #eureka显示的微服务名字

feign: 
  hystrix: 
    enabled: true
        
eureka:
  client: 
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance: 
    instance-id: shop-consumer9001
    prefer-ip-address: true #显示ip