server:
  port: 8003
  
spring:
  application:
    name: shop-pay #eureka显示的微服务名字
    
eureka:
  client:
    service-url: 
      defaultZone: http://localhost:7001/eureka #向此服务中心注册
  instance:
    instance-id: shop-pay8003
    prefer-ip-address: true 